version: "3"

networks:
    fv-proxy:
      driver: bridge
    fv-db-net:
      internal: true
    fv-adm-net:
      internal: true

services:
    nginx:
        image: jwilder/nginx-proxy:alpine
        container_name: nginx
        restart: always
        labels:
            com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: 'true'
        ports:
            - 80:80
            - 443:443
        volumes:
            - ../Proxy/logs/global:/var/log/nginx
            - ../Proxy/conf/proxy.conf:/etc/nginx/conf.d/proxy.conf
            - ../Proxy/vhost:/etc/nginx/vhost.d
            - ../Proxy/passwd:/etc/nginx/htpasswd
            - ../Proxy/data/html:/usr/share/nginx/html
            - ../Proxy/data/certs:/etc/nginx/certs:ro
            - ../Proxy/logs/services:/customlogs
            - /var/run/docker.sock:/tmp/docker.sock:ro
        networks:
            - fv-proxy

    letsencrypt:
        image: jrcs/letsencrypt-nginx-proxy-companion
        container_name: letsencrypt
        volumes:
            - ../Proxy/vhost:/etc/nginx/vhost.d
            - ../Proxy/data/html:/usr/share/nginx/html
            - ../Proxy/data/certs:/etc/nginx/certs:rw
            - /var/run/docker.sock:/var/run/docker.sock:ro
        depends_on:
            - nginx
        networks:
            - fv-proxy
            - fv-db-net
            - fv-adm-net
